# Generated by Django 4.0.5 on 2022-06-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctores',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
        migrations.RenameModel(
            old_name='Posgrados',
            new_name='Posgrado',
        ),
    ]
