# Generated by Django 4.0.5 on 2022-07-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_residencia_delete_posgrado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctores'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profesion',
        ),
    ]
