# Generated by Django 4.0.5 on 2022-07-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_doctor_options_remove_doctor_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(default='', max_length=30, verbose_name='Especialidad del Doctor'),
        ),
    ]
